### ISSUE TITLE
Login page

### ISSUE THREAD

**Issue by ordeh** [tasks-delivery/book-management#1]
# Acceptance criteria:

1. It is possible to join into book management platform

# Link to requirements:
https://github.com/tasks-delivery/book-management/wiki/Login-page

**Comment by TatsianaZhigalko** [comment]
Hello, @ordeh 

Regression/Acceptance testing completed 

link to test-suite: https://docs.google.com/spreadsheets/d/1LIhAnKV8Sb8eHRwrOlc2NL8wb2t8EIDzPRuww_D8fWI/edit?usp=sharing
