### ISSUE TITLE
Add book

### ISSUE THREAD

**Issue by ordeh** [tasks-delivery/book-management#12]
# Acceptance criteria:

1. It is possible to add a book to the system.
2. Book name and category are mandatory.
3. It is possible to add a book without a first name and last name.

# Link to requirements:
https://github.com/tasks-delivery/book-management/wiki/Add-book

**Comment by TatsianaZhyhalka** [comment]
Hello @ordeh

Functions 2 isn't implemented in the task. Books are saved without a name and category. 
A bug report S1.2.1 has been sent to you.

Thanks

**Comment by TatsianaZhigalko** [comment]
Tested
