### ISSUE TITLE
Add book

### ISSUE THREAD

**Issue by ordeh** [tasks-delivery/book-management#14]
![изображение](https://user-images.githubusercontent.com/25455982/99585205-128fb180-29f7-11eb-8ac1-f49f1e8fba92.png)

# Acceptance criteria:

1. It is possible to add a book to the system.
2. Book names and categories are mandatory. The following categories available:
- Detective fiction
- Fantasy
- Science fiction
- Dictionary
3. It is possible to add a book without a first name and last name.
4. The user should understand how to work with the form by a description in hints.
5. The user should be redirected by the system to the Search page after submitting the form.
6. System should not have a book with the same name and category.
7. The Add book page should have a header, that described in common requirements https://github.com/tasks-delivery/book-management/wiki/Common-requirements

# Link to requirements:
https://github.com/tasks-delivery/book-management/wiki/Add-book

**Comment by ordeh** [comment]
It is possible to check all books in the system by https://book-platform-develop.herokuapp.com/books (**It is a temporary solution**).

**Comment by TatsianaZhigalko** [comment]
Hello @ordeh 

Functions 2 and 6 are not implemented in the task. Books are saved without a name and category, and books with the same name and category are also saved

**Comment by ordeh** [comment]
Hi @TatsianaZhyhalka thanks, it was fixed.
Could you re-execute tests?

**Comment by TatsianaZhigalko** [comment]
Hello @ordeh 
Thanks for the quick response
Testing completed successfully

Link https://docs.google.com/spreadsheets/d/1LIhAnKV8Sb8eHRwrOlc2NL8wb2t8EIDzPRuww_D8fWI/edit?usp=sharing
