### ISSUE TITLE
Logout

### ISSUE THREAD

**Issue by ordeh** [tasks-delivery/book-management#16]
It is possible to logout from the system by icon below:
![изображение](https://user-images.githubusercontent.com/25455982/97797005-056a7880-1c2a-11eb-84a9-ead003174136.png)

**Comment by TatsianaZhigalko** [comment]
Hello @ordeh ,
testing completed successfully

Link https://docs.google.com/spreadsheets/d/1LIhAnKV8Sb8eHRwrOlc2NL8wb2t8EIDzPRuww_D8fWI/edit?usp=sharing
