### ISSUE TITLE
Login page

### ISSUE THREAD

**Issue by ordeh** [tasks-delivery/book-management#2]
# Acceptance criteria:

1. It is possible to join into book management platform by 'Join' button

# Link to requirements:
https://github.com/tasks-delivery/book-management/wiki/Login-page

# Link to design: 
https://marvelapp.com/project/5228627/screen/73378501

**Comment by TatsianaZhigalko** [comment]
Hello, @ordeh

Tests for sprint 1.0.0 are ready.

link https://docs.google.com/spreadsheets/d/1LIhAnKV8Sb8eHRwrOlc2NL8wb2t8EIDzPRuww_D8fWI/edit#gid=0
