### ISSUE TITLE
Book search

### ISSUE THREAD

**Issue by ordeh** [tasks-delivery/book-management#3]
# Acceptance criteria:

1. It is possible to filter a book by category, name, or category with a name.
2. It is possible to understand that book is available or not at this moment.

# Link to requirements:
https://github.com/tasks-delivery/book-management/wiki/Search-book-page

**Comment by ordeh** [comment]
It is possible to check book search by GET request to endpoint /books/{name} 
- Path parameter **name** - name of book
- Query parameter **categories** - book category

**Comment by TatsianaZhigalko** [comment]
Tested
