### ISSUE TITLE
Book alert 1

### ISSUE THREAD

**Issue by ordeh** [tasks-delivery/book-management#30]
![изображение](https://user-images.githubusercontent.com/25455982/98043869-06242a00-1e37-11eb-8e3c-e1beef756069.png)

# Acceptance criteria:

1. It is not possible to remove book with user.

# Link to design: 
https://marvelapp.com/prototype/6b86ded/screen/73675394/handoff

# Link to requirements:
https://github.com/tasks-delivery/book-management/wiki/Book-alert-1

**Comment by TatsianaZhigalko** [comment]
Hello @ordeh 
Tested 

link: https://docs.google.com/spreadsheets/d/1dTCHcW0C32LYw3npXC4DRJX4ZKIZoK6CRseYwmLK5qI/edit?usp=sharing
