### ISSUE TITLE
Book dialog 1

### ISSUE THREAD

**Issue by ordeh** [tasks-delivery/book-management#32]
![изображение](https://user-images.githubusercontent.com/25455982/98045095-fdccee80-1e38-11eb-8cd7-ebd674abb185.png)

# Acceptance criteria:

1. User should confirm or cancel remove of book by dialog.

# Link to design: 
https://marvelapp.com/prototype/6b86ded/screen/74179906/handoff

# Link to requirements:
https://github.com/tasks-delivery/book-management/wiki/Book-dialog-1

**Comment by TatsianaZhigalko** [comment]
Hello @ordeh 
Tested

link : https://docs.google.com/spreadsheets/d/1dTCHcW0C32LYw3npXC4DRJX4ZKIZoK6CRseYwmLK5qI/edit?usp=sharing
