### ISSUE TITLE
User authentication

### ISSUE THREAD

**Issue by ordeh** [tasks-delivery/book-management#33]
**Acceptance criteria:**

for register endpoint

- Login, first name, last name and password cannot be empty.
- It is not possible to create the same user.

for login endpoint

- Login and password cannot be empty. 
- login endpoint should have validation for wrong password
- login endpoint should have validation for not existed login

**Comment by ordeh** [comment]
Hi @TatsianaZhigalko 

Please re-check the requirements. I added some updates. in https://github.com/tasks-delivery/book-management/wiki/Login-page and https://github.com/tasks-delivery/book-management/wiki/Registration

Could you update test-cases for UI according to new acceptance criteria?

**Comment by TatsianaZhigalko** [comment]
Hello @ordeh 
Please specify what should happen during registration 
after clicking "Sing in" and after clicking "Create" ?

**Comment by ordeh** [comment]
Hi @TatsianaZhigalko 
After registration user should be redirected to the Login page

**Comment by TatsianaZhigalko** [comment]
Hello @ordeh 

Tested

Link to updated test-cases for UI : https://docs.google.com/spreadsheets/d/1AcGCvLL8JsTIvg-QDPwEGZayiylHTlgGVcdA-lWp3x8/edit?usp=sharing
