### ISSUE TITLE
User authentication

### ISSUE THREAD

**Issue by ordeh** [tasks-delivery/book-management#34]
**Login form:**

![изображение](https://user-images.githubusercontent.com/25455982/101922295-f68ac480-3bde-11eb-9911-f0b93edb1a27.png)

Link to requirements:
https://github.com/tasks-delivery/book-management/wiki/Login-page

**Registration form:**

![изображение](https://user-images.githubusercontent.com/25455982/101921632-4026df80-3bde-11eb-92dc-bbaed1e1941d.png)

Link to requirements:
https://github.com/tasks-delivery/book-management/wiki/Registration

**Comment by TatsianaZhigalko** [comment]
Hello @ordeh 

Tested

Link https://docs.google.com/spreadsheets/d/1AcGCvLL8JsTIvg-QDPwEGZayiylHTlgGVcdA-lWp3x8/edit?usp=sharing
