### ISSUE TITLE
Remove/Edit book and user

### ISSUE THREAD

**Issue by ordeh** [tasks-delivery/book-management#38]
# Acceptance criteria:

1. It is possible to edit book info (name, category, first name, last name)
2. Book names and categories are mandatory. The following categories available:
- Detective fiction
- Fantasy
- Science fiction
- Dictionary
It is not the final category list, in the future will be added more.
3. It is possible to remove book without user
4. System should not have a book with the same name and category.

**Comment by ordeh** [comment]
## Edit book requirest:

Send PUT request to /book/{id} endpoint with model of data as for POST request. Path parameter id is a id of book that we want to edit. 

## Delete book request

Send DELETE request bo /book endpoint with query parameter 'id'. Query parameter id is a id of book that we want to delete.

**Comment by TatsianaZhigalko** [comment]
Hello @ordeh 

I cannot add User's First and Last names.
When sending a request with filled "Name" and "Category" fields, the error "this book exists in the system" appears
When sending a request with empty "Name" and "Category" fields, the error "the field "Name" cannot be empty" appears

It is possible to edit book info only once. Is it ok?

The system has mixed books with and without a user
Currently, only books WITH a user can be deleted.
When trying to delete a book without a user, an error "Book WITH user cannot be removed" appears

**Comment by ordeh** [comment]
Hi @TatsianaZhyhalka 

The behavior for both cases is not right. I'm going to fix this.

**Comment by ordeh** [comment]
Fixed. 

@TatsianaZhyhalka  Could you re-check?

In case '**When sending a request with empty "Name" and "Category" fields, the error "the field "Name" cannot be empty**" appears' it is right behavior.

**Comment by TatsianaZhigalko** [comment]
Hello @ordeh 
Tested
