### ISSUE TITLE
Remove/Edit book and user

### ISSUE THREAD

**Issue by ordeh** [tasks-delivery/book-management#39]
# Acceptance criteria:

1. It is possible to edit book info (name, category, first name, last name)
2. Book names and categories are mandatory. The following categories available:
- Detective fiction
- Fantasy
- Science fiction
- Dictionary
It is not the final category list, in the future will be added more.
3. It is possible to remove book without user
4. System should not have a book with the same name and category.

Requirements:
https://github.com/tasks-delivery/book-management/wiki/Book-profile

Link to design:
https://marvelapp.com/prototype/6b86ded/screen/74691109/handoff

**Comment by TatsianaZhigalko** [comment]
Hello @ordeh 
1.Please specify, when the admin goes to the edit tab, the "Name", "Category" ,"User" fields will be empty?
2.Can a book with a user be edited by name or categories?

**Comment by TatsianaZhigalko** [comment]
Hello @ordeh 

Task  3  doesn't implemented

**Comment by ordeh** [comment]
Hi @TatsianaZhigalko thanks, fixed.

**Comment by TatsianaZhigalko** [comment]
Hello @ordeh 

Tested
