### ISSUE TITLE
Book search

### ISSUE THREAD

**Issue by ordeh** [tasks-delivery/book-management#4]
# Acceptance criteria:

![изображение](https://user-images.githubusercontent.com/25455982/98041996-d9bade80-1e33-11eb-92c8-735b32970b21.png)

1. It is possible to filter a book by category, name, or category with a name.
2. It is possible to understand that book is available or not at this moment by icons in the availability column.
3. The Search book page should have header, that described in common requirements https://github.com/tasks-delivery/book-management/wiki/Common-requirements

# Link to design: 
https://marvelapp.com/project/5228627/screen/73378781

# Link to requirements:
https://github.com/tasks-delivery/book-management/wiki/Search-book-page

**Comment by TatsianaZhigalko** [comment]
Hello
Dear Fedor @ordeh ,
please ,specify what happens with the fields "Book title", "Category" after clicking the button "Filter" ?
Thank you!

**Comment by ordeh** [comment]
Hi @TatsianaZhyhalka 

I updated the requirements, please check this
https://github.com/tasks-delivery/book-management/wiki/Search-book-page

Regards Fedor.

**Comment by TatsianaZhigalko** [comment]
Hello @ordeh 

Requirement "4.Book name and Category should be empty after clicking on the filter button" isn't implemented.

When you open the search page, the entire list of books appears. Is it ok?

**Comment by ordeh** [comment]
Hi @TatsianaZhigalko 

All books can be visible if book name empty and the category not selected.

**Comment by TatsianaZhigalko** [comment]
Hello @ordeh 
The entire list of books appears on the "Book Search" page without clicking the "Filter" button
Is that what you meant?

**Comment by ordeh** [comment]
Hi @TatsianaZhigalko 
Yes

**Comment by ordeh** [comment]
Requirement 4 has been removed because it is bad practice from UI/UX point.

**Comment by TatsianaZhigalko** [comment]
Hello @ordeh 
Tested

link https://docs.google.com/spreadsheets/d/1pJe-XVGOs3hKnXISV6gJRSbJfntiIxI_jX6IlDIttYE/edit?usp=sharing
