### ISSUE TITLE
S1.2.1   The book is saved without a name and category

### ISSUE THREAD

**Issue by TatsianaZhigalko** [tasks-delivery/book-management#40]
Build version:
1.1.0

Information to reproduce:
1. Request - POST
    EndPoint - /book
    Body - {"name":"","categories":[""],"user":{"firstName":"","lastName":""}}
    

Actual result: The book issaved in the system. Status 200;
Expected result: The book is not saved in the system. Error 400;

**Comment by ordeh** [comment]
Cannot reproduce. @TatsianaZhyhalka could you re-check this?

**Comment by TatsianaZhigalko** [comment]
Hello, @ordeh 
Sorry for the inaccuracy.
А book with title and category already exists in the system  - bookId : 11

It is also possible to save the book without a name
Request - POST
EndPoint - /book
Body - {"name":"","categories":["Science fiction"],"user":{"firstname":"","lastname":""}}

**Comment by ordeh** [comment]
Fixed

**Comment by TatsianaZhigalko** [comment]
Hello, @ordeh

Thanks for the quick response. Checked. Bug fixed

Actual result: The book isn't saved in the system. Error 400;
Expected result: The book isn't saved in the system. Error 400;
