### ISSUE TITLE
S1.2.2 Book with sign '?' is not found

### ISSUE THREAD

**Issue by TatsianaZhigalko** [tasks-delivery/book-management#42]
Build version:
1.2.0

Information to reproduce:
Request - Get
EndPoint - /book

Path parameter  - why?
Query parameter  - ?categories=Fantasy

Actual result: The book isn't shown. Error 400;
Expected result: The book is shown. Status 200;

**Comment by ordeh** [comment]
Fixed.

'name' was reworked from path parameter to query parameter. Also, at this moment endpoint for getting all books have been changed to /allBooks

**Comment by TatsianaZhigalko** [comment]
Hello, @ordeh

Thanks for the quick response. Checked. Bug fixed.

Actual result: The book is shown. Status 200;
Expected result: The book is shown. Status 200;
