### ISSUE TITLE
S1.2.3 The category of books that doesn't exist in the system is saved

### ISSUE THREAD

**Issue by TatsianaZhigalko** [tasks-delivery/book-management#43]
Build version:
1.1.0

Information to reproduce:

Request - POST
EndPoint - /book
Body - {"name":"NAME123","categories":["NAME123"],"user":{"firstName":"","lastName":""}}

Actual result: The book isn't saved in the system. Error 400;
Expected result: The book is saved in the system. Status 200;

**Comment by ordeh** [comment]
Fixed.

The expected result for this case should be 404 (not found), because we try to find a book by not existed category.

**Comment by TatsianaZhigalko** [comment]
Hello, @ordeh 

Thanks for the quick response.Checked. Bug fixed

Actual result: The book isn't saved in the system. Error 404;
Expected result: The book isn't saved in the system. Error 404;
