### ISSUE TITLE
S1.2.4  Book with special characters in the title isn't found

### ISSUE THREAD

**Issue by TatsianaZhigalko** [tasks-delivery/book-management#44]
Build version:
1.2.0

Information to reproduce:
Request - Get
EndPoint - /book

Path parameter - !@^&#*)@!^%&*@#!%%)@!)&^!%!)@*&3785350
Query parameter - ?categories=Fantasy

Actual result: The book isn't shown. Error 400;
Expected result: The book is shown. Status 200;

**Comment by ordeh** [comment]
It is not a bug.

Web frameworks may provide methods for parsing multiple parameters in the query string, separated by some delimiter.[4] In the example URL below, multiple query parameters are separated by the ampersand, "&":

https://example.com/path/to/page?name=ferret&color=purple

**Comment by TatsianaZhigalko** [comment]
Hello, @ordeh 

Thanks for the explanation
