### ISSUE TITLE
S1.2.5 A scrolling line appears during character input

### ISSUE THREAD

**Issue by TatsianaZhigalko** [tasks-delivery/book-management#45]
Build version:
1.1.0

Environment:
Google Chrome v86

Steps to reproduce:
1.Tap on the " Join " button;
2.Tap on the " Add book " button at the "Book search" page;
3.Enter the title of the book in the "Book Title" field;

Actual result: Scrolling line appears and disappears, changing the page scale;
Expected result: The page scale remains unchanged

![Безымянный](https://user-images.githubusercontent.com/72810412/98669166-0d30c800-2362-11eb-9958-e884776f5ba3.png)
;

**Comment by ordeh** [comment]
Cannot reproduce in Chrome 86.0.4240.183 

![изображение](https://user-images.githubusercontent.com/25455982/99001164-70318300-254b-11eb-9669-91897fcec684.png)

**Comment by TatsianaZhigalko** [comment]
Hello, @ordeh 
The bug is still reproducible on the test device.

OS: Windows 10
Chrome 86.0.4240.193
Screen Resolution 1536 x 864
Browser Window 1536 x 722

**Comment by ordeh** [comment]
Not a bug, because that's predictable behavior for this Browser Window size.

![изображение](https://user-images.githubusercontent.com/25455982/99196527-f04f2700-279d-11eb-8ff4-86ee3c9a3856.png)

**Comment by TatsianaZhigalko** [comment]
Hello @ordeh 

Thank you!
