### ISSUE TITLE
I 1.2  Prohibit using only spaces in the book title.

### ISSUE THREAD

**Issue by TatsianaZhigalko** [tasks-delivery/book-management#49]
Module: Add Book

The user can save the book by entering only spaces in the "Book Name" field.

Improvement: Forbid using a space several times in a row in the "Book name" field

**Comment by ordeh** [comment]
@TatsianaZhyhalka 

Do you mean only spaces? because as you describe we should not be saved book with name for example, 'Test  test'

**Comment by TatsianaZhigalko** [comment]
Hello, @ordeh 

Yes.  Forbid using only spaces in the "Book name" field.

**Comment by TatsianaZhigalko** [comment]
Hello @ordeh 
Thanks 
Tested, spaces are not allowed.
