### ISSUE TITLE
Add edit and remove icons

### ISSUE THREAD

**Issue by ordeh** [tasks-delivery/book-management#59]
As Admin I want to have a possibility to remove or edit the book.

Remove and edit icons should be visible only for admin **(At this moment icons should be visible to everyone)**

Also, It is possible to navigate to the Edit book page by edit Icon in the search grid.

![изображение](https://user-images.githubusercontent.com/25455982/99584125-947edb00-29f5-11eb-815c-7c3bbcf1b806.png)

**Comment by TatsianaZhigalko** [comment]
Hello @ordeh 
Tested

link https://docs.google.com/spreadsheets/d/1pJe-XVGOs3hKnXISV6gJRSbJfntiIxI_jX6IlDIttYE/edit?usp=sharing
