### ISSUE TITLE
Add book author

### ISSUE THREAD

**Issue by ordeh** [tasks-delivery/book-management#67]
**Acceptance criteria**:

- Book should have one or more authors

**Requirements**:
https://github.com/tasks-delivery/book-management/wiki/Add-book

**Body example**:

{"name":"sdfaert","categories":["Detective fiction"],"user":{"firstName":"ert","lastName":"ert"}, "authors":[{"firstName":"ert","lastName":"ert"}, {"firstName":"esdf","lastName":"ersdft"}]}

**Comment by ordeh** [comment]
Each book will be created with fake author data, it is a temporary solution.

          firstName:'First name test',
            lastName:'Last name test'

**Comment by TatsianaZhigalko** [comment]
Tested
