### ISSUE TITLE
Application deployment

### ISSUE THREAD

**Issue by ordeh** [tasks-delivery/book-management#7]
Application deployment should use the following tools:
- Travis CI
- Heroku

**Comment by ordeh** [comment]
Done.

The following links should be opened without error on front-end and back-end sides:

- https://book-platform-release.herokuapp.com/
- https://book-platform-develop.herokuapp.com/

**Comment by TatsianaZhigalko** [comment]
Hello @ordeh 

Application deployment check completed successfully.
Pages load without errors.
