### ISSUE TITLE
Book location

### ISSUE THREAD

**Issue by ordeh** [tasks-delivery/book-management#70]
Each book should have row and number positions in the library.

Model example:
{"name":"dfs","categories":["Science fiction"],"user":{"firstName":"","lastName":""},"location":{"variety":"A","number":"2"},"authors":[{"firstName":"First name test","lastName":"Last name test"}]}

At this moment we will send from front-end side  fake data {variety:'A', number:'2'} ,to back-end. It is a temporary solution, full logic will be implemented in the ticker for a front-end side.

**Comment by TatsianaZhigalko** [comment]
Tested
