### ISSUE TITLE
User email for notification

### ISSUE THREAD

**Issue by ordeh** [tasks-delivery/book-management#72]
Email is not a required field.

Model example:
{"name":"hgfj","categories":["Detective fiction"],"user":{"firstName":"","lastName":"", "email":"test@mail.ru"},"location":{"variety":"A","number":"2"},"authors":[{"firstName":"First name test","lastName":"Last name test"}]}

**Comment by TatsianaZhigalko** [comment]
Hello @ordeh 
 Unfortunately I cannot test this. 
I opened a bug  S1.6.5

**Comment by ordeh** [comment]
Hi @TatsianaZhigalko 

please see https://github.com/tasks-delivery/book-management/issues/96

**Comment by TatsianaZhigalko** [comment]
Hello @ordeh 
Tested
