### ISSUE TITLE
Book return date

### ISSUE THREAD

**Issue by ordeh** [tasks-delivery/book-management#73]
It is possible to set book return date, this field is not mandatory.

Model example:
{"name":"ssdfadaf", "returnDate":"2020-12-06 20:21:34.231", "categories":["Fantasy"],"user":{"firstName":"","lastName":""},"location":{"variety":"A","number":"2"},"publisher":{"name":"Publisher Home At Moscow","date":"2020-12-06 20:21:34.231"},"authors":[{"firstName":"First name test","lastName":"Last name test"}]}

**Comment by TatsianaZhigalko** [comment]
Hello @ordeh 
 Unfortunately I cannot test this. 
I opened a bug  S1.6.5

**Comment by ordeh** [comment]
Hi @TatsianaZhigalko 

please see https://github.com/tasks-delivery/book-management/issues/96

**Comment by TatsianaZhigalko** [comment]
Hello @ordeh 
Thank you
Tested
