### ISSUE TITLE
Publisher info

### ISSUE THREAD

**Issue by ordeh** [tasks-delivery/book-management#77]
Each book should have the name of the publisher's organization and date of publishing.

Model example:

{"name":"sdaf","categories":["Fantasy"],"user":{"firstName":"","lastName":""},"location":{"variety":"A","number":"2"},"publisher":{"name":"Publisher Home At Moscow","date":"2020-12-06 20:21:34.231"},"authors":[{"firstName":"First name test","lastName":"Last name test"}]}

At this moment we will send from front-end side fake data {"name":"Publisher Home At Moscow","date":"2020-12-06 20:21:34.231"} ,to back-end. It is a temporary solution, full logic will be implemented in the ticker for a front-end side.

**Comment by TatsianaZhigalko** [comment]
Tested
