### ISSUE TITLE
JPA relations refactoring

### ISSUE THREAD

**Issue by ordeh** [tasks-delivery/book-management#81]
The following params were changed:

authorId to id;
userId to id
bookId to id
locationId to id
publisherId to id
category array to model {"id": "your category id", "name":"your category name"}

Example of model:

![изображение](https://user-images.githubusercontent.com/25455982/101294386-fb8af500-3827-11eb-96fe-314313fec9ff.png)

**Comment by TatsianaZhigalko** [comment]
Tested
