### ISSUE TITLE
Add book type

### ISSUE THREAD

**Issue by ordeh** [tasks-delivery/book-management#85]
Each book should have book type.

Model example:

![изображение](https://user-images.githubusercontent.com/25455982/101395795-7eb95300-38db-11eb-8515-2b5aa32959ce.png)

At this moment we will send from front-end side fake data {id: 1, name: "Free book"} ,to back-end. It is a temporary solution, full logic will be implemented in the ticker for a front-end side.

**Comment by TatsianaZhigalko** [comment]
Hello @ordeh 
Please specify if the ID in the row of the "bookTypes" should correspond to the ID of the book in the system?

**Comment by ordeh** [comment]
Hi @TatsianaZhigalko 

No, bookType id it will be generated automatically by the system after creating as a separated parameter.

**Comment by TatsianaZhigalko** [comment]
Hello @ordeh 
Thanks, 
tested
