### ISSUE TITLE
About page

### ISSUE THREAD

**Issue by ordeh** [tasks-delivery/book-management#87]
# About page

![изображение](https://user-images.githubusercontent.com/25455982/101934395-969c1a00-3bee-11eb-9f55-49b7abde2770.png)

# Acceptance criteria:

1. Each hint can be expanded or collapse
2. The About page should have a header, that described in common requirements https://github.com/tasks-delivery/book-management/wiki/Common-requirements

Link to requirements:
https://github.com/tasks-delivery/book-management/wiki/About-page

**Comment by TatsianaZhigalko** [comment]
Hello @ordeh
Please specify by criterion number 2.
Common requirements include only "Home", "About" , "Contact Us" headers.
The "About" page contains "Home", "About", "Features", "Pricing", "Contact us" headers.
Please clarify will common requirements be updated?

**Comment by TatsianaZhigalko** [comment]
Hello @ordeh 
Tested

Link: https://docs.google.com/spreadsheets/d/1AcGCvLL8JsTIvg-QDPwEGZayiylHTlgGVcdA-lWp3x8/edit?usp=sharing
