### ISSUE TITLE
Contact page

### ISSUE THREAD

**Issue by ordeh** [tasks-delivery/book-management#88]
![изображение](https://user-images.githubusercontent.com/25455982/101934309-766c5b00-3bee-11eb-8a47-5fb42088f5ee.png)

# Acceptance criteria:

1. Each section can be expanded or collapse
2. The Contact page should have a header, that described in common requirements https://github.com/tasks-delivery/book-management/wiki/Common-requirements

Link to requirements:
https://github.com/tasks-delivery/book-management/wiki/Contact-page

**Comment by TatsianaZhigalko** [comment]
Hello @ordeh 
Please specify by criterion number 2.
Common requirements include only "Home", "About" , "Contact Us" headers. 
The "Contact us" page contains "Home", "About", "Features", "Pricing", "Contact us" headers. 
Please clarify will  common requirements  be updated?

**Comment by ordeh** [comment]
Hi @TatsianaZhigalko yes. I'm going to update header wiki. Features a Prinig tabs will be removed. The same for ticket #87

**Comment by TatsianaZhigalko** [comment]
Hello @ordeh 
Tested

link : https://docs.google.com/spreadsheets/d/1AcGCvLL8JsTIvg-QDPwEGZayiylHTlgGVcdA-lWp3x8/edit?usp=sharing
