### ISSUE TITLE
S1.6.3 Book search results are duplicated

### ISSUE THREAD

**Issue by TatsianaZhigalko** [tasks-delivery/book-management#95]
Build version:
1.6.0

Reproducibility: sometimes

Steps to reproduce:

  1. Tap on the "Join" button;
  2. Tap on the "Filter" button;

Actual result: Book search results are duplicated.
Expected result: Books are shown in a single copy.

![image](https://user-images.githubusercontent.com/72810412/101500597-bed21180-397f-11eb-89e3-b69fbbf4e4b4.png)

**Comment by ordeh** [comment]
@TatsianaZhigalko 

Hi, thanks. I'm going to research this issue.

**Comment by ordeh** [comment]
Hi @TatsianaZhigalko  it is a performance issue. I added a progress bar to avoid this case.

![изображение](https://user-images.githubusercontent.com/25455982/101841783-b3394300-3b57-11eb-961c-4d5637809454.png)

**Comment by TatsianaZhigalko** [comment]
Hello @ordeh 
Tested
