### ISSUE TITLE
S1.6.4 It is impossible to add a book to the system

### ISSUE THREAD

**Issue by TatsianaZhigalko** [tasks-delivery/book-management#96]
Build version:
1.6.0

Information to reproduce:

Request :  POST
Endpoint:  /book

Body
{"name":"111","categories":["Fantasy"],"user":{"firstName":"","lastName":""},"location":{"variety":"A","number":"2"},"publisher":{"name":"Publisher Home At Moscow","date":"2020-12-06 20:21:34.231"},"authors":[{"firstName":"First name test","lastName":"Last name test"}]}

Actual result: The book isn't saved in the system. Error 500;
Expected result: The book is  saved in the system. Status 200 ;

**Comment by ordeh** [comment]
@TatsianaZhigalko 

You made a mistakes in request body.

Have look example below:
{"name":"1111","categories":[{"name":"Fantasy"}],"user":{"firstName":"","lastName":""},"location":{"variety":"A","number":"2"},"publisher":{"name":"Publisher Home At Moscow","date":"2020-12-06 20:21:34.231"},"authors":[{"firstName":"First name test","lastName":"Last name test"}]}

**Comment by TatsianaZhigalko** [comment]
Hello @ordeh 
Thank you
