### ISSUE TITLE
S 1.6.5 It is impossible to edit book info

### ISSUE THREAD

**Issue by TatsianaZhigalko** [tasks-delivery/book-management#97]
Build version:
1.6.0

Information to reproduce:

Request : PUT
Endpoint: /book/{id}

Body
{"name":"Test test","categories":["Fantasy"],"user":{"firstName":"","lastName":""},"location":{"variety":"A","number":"2"},"publisher":{"name":"Publisher Home At Moscow","date":"2020-12-06 20:21:34.231"},"authors":[{"firstName":"First name test","lastName":"Last name test"}]}

Actual result: The book isn't saved in the system. Error 500;
Expected result: The book is saved in the system. Status 200 ;

**Comment by ordeh** [comment]
@TatsianaZhigalko 
The same  as in https://github.com/tasks-delivery/book-management/issues/96

**Comment by TatsianaZhigalko** [comment]
Hello @ordeh 
Thank you
